//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Wing_Visual_Builder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("X_Wing_Visual_Builder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 201£5£0£Dagger Squadron Pilot£4£A unique gyrostabilization surrounds the B-Wing&apos;s cockpit, ensuring that the pilot always remains stationary during combat.£11,6,4,4£24££2£0
        ///907£39£0£Resistance Sympathizer£3£After the destruction of the Hosnian system, some spacers willingly aided the Resistance against the malevolent First Order.£5,9,9£38££2£0
        ///4105£48£0£Imperial Trainee£1£After the Republic fell and as the Empire rose, the new galactic government required thousands of new pilots to replace the decommissio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PilotDatabase {
            get {
                return ResourceManager.GetString("PilotDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1£2£A-Wing£2£0£0£2£3£2£2£6,12,2,5£2
        ///2£3£ARC-170£2£0£0£2£1£6£3£6,12£2
        ///3£4£Attack Shuttle£2£0£0£3£2£2£2£6,1,5£2
        ///4£5£B-Wing£2£0£0£3£1£3£5£6,12,1£2
        ///5£7£E-Wing£2£0£0£3£3£2£3£6,12,1,5£2
        ///6£13£HWK-290£2£0£0£1£2£4£1£6,12£2
        ///7£18£K-Wing£2£0£0£2£1£5£4£6,12,11£2
        ///8£25£T70 X-Wing£2£0£1£3£2£3£3£6,12,2£2
        ///9£35£VCX-100£3£0£0£4£0£10£6£6,12,5£2
        ///10£37£X-Wing£2£0£1£3£2£3£2£6,12£2
        ///11£38£Y-Wing£2£0£0£2£1£5£3£6,12£2
        ///12£39£YT-1300£3£0£0£3£1£8£5£6,12£2
        ///13£40£YT-2400£3£0£0£2£2£5£5£6,12,1£2
        ///14£42£Z-95 Headhunter£2£0£0£2£2£2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShipsDatabase {
            get {
                return ResourceManager.GetString("ShipsDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1035£2£4£Expertise£When attacking, if you are not stressed, you may change all of your focus results to hit results.££1£1£1£0£0£0£1£0£0£0£££££££
        ///1008£2£4£Expose£ACTION: Until the end of the round, increase your primary weapon value by 1 and decrease your agility value by 1.££1£1£1£0£0£0£1£0£0£0£££££££
        ///1013£2£4£Opportunist£When attacking, if the defender does not have any focus or evade tokens, you may receive 1 stress token to roll 1 additional attack die.@You cannot use this ability if you have any stres [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpgradeDatabase {
            get {
                return ResourceManager.GetString("UpgradeDatabase", resourceCulture);
            }
        }
    }
}
